# Generated by Django 5.1.1 on 2024-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('need', models.CharField(max_length=200)),
                ('loan_tenure', models.CharField(max_length=200)),
                ('employment_status', models.CharField(max_length=200)),
                ('reason_for_loan', models.CharField(max_length=200)),
                ('employment_address', models.CharField(max_length=200)),
            ],
        ),
    ]
